% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={lecture 2},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{lecture 2}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

次のRのプログラムは，2つのグループ（非肥満グループlean，肥満グループobese）におけるアウトカムYである総エネルギー消費量（MJ/day）データを作るものである．

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lean }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{6.13}\NormalTok{,}\FloatTok{7.05}\NormalTok{,}\FloatTok{7.48}\NormalTok{,}\FloatTok{7.48}\NormalTok{,}\FloatTok{7.53}\NormalTok{,}\FloatTok{7.58}\NormalTok{,}\FloatTok{7.9}\NormalTok{,}\FloatTok{8.08}\NormalTok{,}\FloatTok{8.09}\NormalTok{,}\FloatTok{8.11}\NormalTok{,}\FloatTok{8.40}\NormalTok{, }\FloatTok{10.15}\NormalTok{,}\FloatTok{10.88}\NormalTok{)}
\NormalTok{obese }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{8.79}\NormalTok{,}\FloatTok{9.19}\NormalTok{,}\FloatTok{9.21}\NormalTok{,}\FloatTok{9.68}\NormalTok{,}\FloatTok{9.69}\NormalTok{,}\FloatTok{9.97}\NormalTok{,}\FloatTok{11.51}\NormalTok{,}\FloatTok{11.85}\NormalTok{,}\FloatTok{12.79}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

Rのfunction関数を用いて，次の4つのマクロ関数を作成せよ．

(1)変数Yについて，1つの群の母平均の95\%信頼区間を計算する．
(2)変数Yについて，1つの群の母平均の検定を行う．
(3)変数Yについて，独立な2つの群の母平均の差の95\%信頼区間を計算する．
(4)変数Yについて，独立な2つの群の母平均の検定（両側検定）を行う．

(1)変数Yについて，1つの群の母平均の95\%信頼区間を計算する．

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ci\_1mean }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(dat, ci\_lev)}
\NormalTok{\{}
\NormalTok{  n }\OtherTok{=} \FunctionTok{length}\NormalTok{(dat)}
\NormalTok{  tval }\OtherTok{=} \FunctionTok{qt}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{((}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{ci\_lev)}\SpecialCharTok{/}\DecValTok{2}\NormalTok{), n}\DecValTok{{-}1}\NormalTok{)}
\NormalTok{  mean1 }\OtherTok{=} \FunctionTok{mean}\NormalTok{(dat)}
\NormalTok{  sd1 }\OtherTok{=} \FunctionTok{sd}\NormalTok{(dat)}
  \FunctionTok{return}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\AttributeTok{nmsd =} \FunctionTok{c}\NormalTok{(n, mean1, sd1),}
              \AttributeTok{civals =} \FunctionTok{c}\NormalTok{(mean1 }\SpecialCharTok{{-}}\NormalTok{ tval}\SpecialCharTok{*}\NormalTok{sd1}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n),}
\NormalTok{              mean1}\SpecialCharTok{+}\NormalTok{tval}\SpecialCharTok{*}\NormalTok{sd1}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)),}
              \AttributeTok{ci\_lev=}\NormalTok{ci\_lev))}
  
\NormalTok{\}}

\FunctionTok{ci\_1mean}\NormalTok{(}\AttributeTok{dat=}\NormalTok{lean, }\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $nmsd
## [1] 13.000000  8.066154  1.238080
## 
## $civals
## [1] 7.317990 8.814318
## 
## $ci_lev
## [1] 0.95
\end{verbatim}

上記実行結果を算出すると、 7.317990 \textless{} \(\mu\)
\textless8.814318　となる。

(2)変数Yについて，1つの群の母平均の検定を行う．

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test.lean }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(dat, m0)}
\NormalTok{\{}
\NormalTok{  n }\OtherTok{=} \FunctionTok{length}\NormalTok{(dat)}
\NormalTok{  df }\OtherTok{=}\NormalTok{ n}\DecValTok{{-}1}
\NormalTok{  t }\OtherTok{=} \FunctionTok{abs}\NormalTok{((}\FunctionTok{mean}\NormalTok{(dat)}\SpecialCharTok{{-}}\NormalTok{m0)}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{sd}\NormalTok{(dat)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)))}
\NormalTok{  pvalue }\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pt}\NormalTok{(t, df))}\SpecialCharTok{*}\DecValTok{2}
  \FunctionTok{return}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\AttributeTok{df=}\NormalTok{df,}\AttributeTok{t=}\NormalTok{t,}\AttributeTok{pvalue=}\NormalTok{pvalue))}
\NormalTok{\}}

\FunctionTok{test.lean}\NormalTok{(}\AttributeTok{dat =}\NormalTok{ lean, }\AttributeTok{m0=}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $df
## [1] 12
## 
## $t
## [1] 5.631769
## 
## $pvalue
## [1] 0.0001104242
\end{verbatim}

pvalue = 0.0001104242 より帰無仮説は棄却される。

(3)変数Yについて，独立な2つの群の母平均の差の95\%信頼区間を計算する．

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test.lean\_obese }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(dat1,dat2,ci\_lev)}
\NormalTok{\{}
\NormalTok{  pooled }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(((}\FunctionTok{length}\NormalTok{(dat1)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(dat1) }\SpecialCharTok{+}\NormalTok{ (}\FunctionTok{length}\NormalTok{(dat2) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{ )}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(dat2))}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{length}\NormalTok{(dat1) }\SpecialCharTok{+} \FunctionTok{length}\NormalTok{(dat2) }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{))}
\NormalTok{  t\_den }\OtherTok{=}\NormalTok{ pooled}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\FunctionTok{length}\NormalTok{(dat1)}\SpecialCharTok{+}\DecValTok{1}\SpecialCharTok{/}\FunctionTok{length}\NormalTok{(dat2))}
\NormalTok{  t\_num }\OtherTok{=} \FunctionTok{mean}\NormalTok{(dat1)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(dat2)}
\NormalTok{  t }\OtherTok{=}\NormalTok{ t\_num}\SpecialCharTok{/}\NormalTok{t\_den}
\NormalTok{  df }\OtherTok{=} \FunctionTok{length}\NormalTok{(dat1) }\SpecialCharTok{+} \FunctionTok{length}\NormalTok{(dat2) }\SpecialCharTok{{-}}\DecValTok{1}
\NormalTok{  under\_score }\OtherTok{=} \FunctionTok{qt}\NormalTok{(ci\_lev, df)}
\NormalTok{  over\_score }\OtherTok{=} \FunctionTok{qt}\NormalTok{(ci\_lev,df,}\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
  \FunctionTok{return}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\AttributeTok{df=}\NormalTok{df, }\AttributeTok{t=}\NormalTok{t, }\AttributeTok{under\_score =}\NormalTok{ under\_score, }\AttributeTok{over\_score =}\NormalTok{ over\_score))}
\NormalTok{\}}

\FunctionTok{test.lean\_obese}\NormalTok{(}\AttributeTok{dat1 =}\NormalTok{ lean, }\AttributeTok{dat2 =}\NormalTok{ obese, }\AttributeTok{ci\_lev =} \FloatTok{0.025}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $df
## [1] 21
## 
## $t
## [1] -3.945565
## 
## $under_score
## [1] -2.079614
## 
## $over_score
## [1] 2.079614
\end{verbatim}

上記より95\%信頼区間は

※t.test(lean, obese, var.equal = T)

を実施した際の結果を表示 -3.411451 \textless{} \(\mu\) \textless{}
-1.051796

(4)変数Yについて，独立な2つの群の母平均の検定（両側検定）を行う

上記を計算した結果 t = -3.9456
となり、-3.411451よりも大きい値となるため、有意差があると判断する。

\end{document}
